### ISSUE TITLE
DnsResolver: Many blocked threads

### ISSUE THREAD

**Issue by deniaa** [vostok/datacenters#1]
If multiple threads come to resolve same hostname and cache is not initialized, all this threads will launch ResolveAndUpdateCacheAsync task. Moreover all threads will wait completion of this task syncronously. This can lead to thread pool starvation.

```
if (cache.TryGetValue(hostname, out var cacheEntry))
{
...
 }

var resolveTask = ResolveAndUpdateCacheAsync(hostname, currentTime);
return resolveTask.Wait(resolveTimeout) ...
```

The first and easy solution may be caching task and awaiting result from cached task.

**Comment by iloktionov** [comment]
Fixed in https://github.com/vostok/datacenters/commit/e58f4451977c09f59becf002c556a76dac79090a and https://github.com/vostok/datacenters/commit/abf0d2d247bbe88e4b82399cb7f73d2764d0dc3e
